version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: npm run version-packages
          name: version lib
      - run:
          command: npm run publish-packages
          name: publish lib
      - run:
          name: Commit and Push Changes
          command: |
            git add .
            git commit -m "Changeset version and publish"
            git push --follow-tags

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main 
