version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          name: Configure Git User Identity
          command: |
            git config --global user.name "manxeguin"
            git config --global user.email "manxeguin1987@gmail.com"
      - run:
          name: Log in to npm
          command: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
          environment:
            NPM_TOKEN: $NPM_TOKEN

  deploy:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Configure Git User Identity
          command: |
            git config --global user.name "manxeguin"
            git config --global user.email "manxeguin1987@gmail.com"
      - run:
          name: Log in to npm
          command: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
          environment:
            NPM_TOKEN: $NPM_TOKEN

      - run:
          name: Check for Changesets
          command: |
            if [ -n "$(find . -name '*.md' -path './.changeset/*')" ]; then
              echo "Changesets found."
              echo 'SET_DEPLOY_VARIABLE=true' >> $BASH_ENV

            else
              echo "No changesets found."
            fi

      - run:
          name: Deploy if Changesets Exist
          command: |
            if [ "$SET_DEPLOY_VARIABLE" = "true" ]; then
              echo "Deploying..."
              npm run version-packages
              npm run publish-packages
              git add .
              git commit -m "Commit changes"
              git push --follow-tags
            else
              echo "Skipping deploy."
            fi


workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main 
